// Browser Local Storage keys
export const THEME_MODE_STORAGE_KEY = '__THEME_MODE_KEY__'
export const SESSION_TOKEN_STORAGE_KEY = '__SESSION_TOKEN_KEY__'
export const LANGUAGE_SELECTED_STORAGE_KEY = 'LANGUAGE_SELECTED_STORAGE_KEY'
