import { BonusType, IBonus } from '../../types/bonus'

function computedBonus<T extends keyof typeof percentageBonusType>(
  playerBonus: { bonus: IBonus }[],
  bonusName: T
): number
function computedBonus<T extends keyof typeof numericBonusType>(
  playerBonus: { bonus: IBonus }[],
  bonusName: T
): number
function computedBonus<T extends keyof typeof activatableBonusType>(
  playerBonus: { bonus: IBonus }[],
  bonusName: T
): boolean
function computedBonus<T extends keyof typeof bonusTypes>(
  playerBonus: { bonus: IBonus }[],
  bonusName: T
): number | boolean {
  const BonusType = bonusTypes[bonusName]

  const isNumericBonus = BonusType === 'PERCENTAGE_BONUS_TYPE' || BonusType === 'NUMERIC_BONUS_TYPE'

  if (isNumericBonus) {
    return playerBonus.reduce(
      (computedBonus, playerBonus) => {
        const bonus = playerBonus.bonus[bonusName] || 0
        return computedBonus + (bonus as number)
      },
      BonusType === 'PERCENTAGE_BONUS_TYPE' ? BASE_PERCENTAGE_BONUS : BASE_NUMERIC_BONUS
    ) as number
  }

  return playerBonus.some((playerBonus) => playerBonus.bonus[bonusName] === true) as boolean
}

export default computedBonus

export const BASE_PERCENTAGE_BONUS = 100
export const BASE_NUMERIC_BONUS = 0
export const BASE_ACTIVATABLE_BONUS = false

export const percentageBonusType = {
  RESEARCH_BONUS: 'PERCENTAGE_BONUS_TYPE',
  RESOURCE_PRODUCTION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_ATTACK_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SHIELD_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPEED_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_CARGO_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_BUILDING_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_ATTACK_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_SHIELD_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_TRAINING_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_ATTACK_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_SHIELD_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_BUILDING_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_STARFIGHTER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_CARRIER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_CRUISER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_DESTROYER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_CARGO_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_FRIGATE_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_BOMBER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_BATTLE_STATION_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_HULL_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_HULL_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SHIELD_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_HEALTH_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_HEALTH_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_SHIELD_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_HULL_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_SHIELD_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE'
}

export const numericBonusType = {
  EXTRA_PLANETS_BONUS: 'NUMERIC_BONUS_TYPE',
  MAX_FLEETS_ALLOWED_BONUS: 'NUMERIC_BONUS_TYPE'
}

export const activatableBonusType = {
  STEALTH_FLEETS_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  STEALTH_FLEETS_DETECTION_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  INTERGALACTIC_TRAVEL_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  FLEET_SHIELD_PIERCING_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  TROOPS_SHIELD_PIERCING_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  DEFENSES_SHIELD_PIERCING_BONUS: 'ACTIVATABLE_BONUS_TYPE'
}

export const bonusTypes: Record<keyof IBonus, BonusType> = {
  RESEARCH_BONUS: 'PERCENTAGE_BONUS_TYPE',
  RESOURCE_PRODUCTION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  STEALTH_FLEETS_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  STEALTH_FLEETS_DETECTION_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  EXTRA_PLANETS_BONUS: 'NUMERIC_BONUS_TYPE',
  INTERGALACTIC_TRAVEL_BONUS: 'ACTIVATABLE_BONUS_TYPE',

  // Fleet Bonus
  FLEET_ATTACK_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_HULL_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_HULL_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SHIELD_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SHIELD_PIERCING_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  FLEET_SHIELD_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPEED_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_CARGO_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_BUILDING_BONUS: 'PERCENTAGE_BONUS_TYPE',
  MAX_FLEETS_ALLOWED_BONUS: 'NUMERIC_BONUS_TYPE',

  // Troops Bonus
  TROOPS_ATTACK_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_HEALTH_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_HEALTH_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_SHIELD_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_SHIELD_PIERCING_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  TROOPS_SHIELD_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  TROOPS_TRAINING_BONUS: 'PERCENTAGE_BONUS_TYPE',

  // Defenses Bonus
  DEFENSES_ATTACK_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_HULL_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_SHIELD_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_SHIELD_PIERCING_BONUS: 'ACTIVATABLE_BONUS_TYPE',
  DEFENSES_SHIELD_REGENERATION_BONUS: 'PERCENTAGE_BONUS_TYPE',
  DEFENSES_BUILDING_BONUS: 'PERCENTAGE_BONUS_TYPE',

  // Capture Units Bonus
  FLEET_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_STARFIGHTER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_CARRIER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_CRUISER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_DESTROYER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_CARGO_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_FRIGATE_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_BOMBER_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE',
  FLEET_SPACE_BATTLE_STATION_CAPTURE_BONUS: 'PERCENTAGE_BONUS_TYPE'
}
